### ISSUE TITLE
How to snapshoot geckoSUSE in usb for personal distribution?

### ISSUE THREAD

**Issue by penguin67** [geckolinux/geckolinux-project#116]
Seems that I have a serious intention to stay longer in SUSE . 

Years ago I started to use GeckoLinux with XFCE desktop , static version. From some weeks I primary use in my laptop (GeckoLinux Next and GeckoLinux Tumbleweed KDE). Really great. Stable, fast and pretty. I have enough experience now in how to backup and restore my Linux. Different ways of this.

Times ago I tried also to produce my SUSE version from SUSE build, that was so simple . Since that, service was stopped and upgraded to another version I never tried. 

I  ask the creator of GeckoLinux. It is possible to have an utility that produce a snapshot ISO of personal running GeckoLinux. Or what kind of utility you recommend ? A similar utility that offered from PCLinuxOS ,MX Linux  or Sparky Linux ( in other words: remastering of my GeckoLInux). I searched on Internet but no results. Somewhere a media yast plugin is recommended. I would like to produce my ISO snapshot , put in USB and use as GeckoLinux installer for myself or my friends. 

Thanks for your work and effort. 

P.S. 
I installed GeckoLinux from iso files that I get from site, updated to the latest and use it as my every day Linux OS. 

Some advice :

**GeckoLinux Static.**
- Install
- Use the follow way to update GeckoLinux Static (from SUSE 15 to SUSE 15.1)

https://en.opensuse.org/SDB:System_upgrade

(Static versions after updating to GeckoLinux 15.1, should be upgraded only by This method : Open Terminal and run **sudo zypper up** (up meaning update))

The next dup (distro upgrade will be when the leap 15.2 will be available or in the cases when you want to install a new kernel different from default Suse Leap 15.1 kernel

(see here : https://www.addictivetips.com/ubuntu-linux-tips/install-new-linux-kernel-versions-on-opensuse-leap/ )

but I will recommend stable Kernel ( that will be default kernel for SUSE leap 15.2)

zypper ar -f http://download.opensuse.org/repositories/Kernel:/stable/standard/ kernel-repo

instead of

zypper ar -f http://download.opensuse.org/repositories/Kernel:/HEAD/standard/ kernel-repo

that is the newest Kernel around ( suppose that is used by SUSE Tumbleweed)

**GeckoLinux Rolling:**

- Install
- Update method  > Open terminal and run **sudo zypper dup** (dup meaning - distro upgrade)

Actually I use qt4-fsarchiver to produce regular GeckoLinux backups to a second partition (backup and restore requires  just couple of minutes in a SSD ). The same can be achieved  by using gnome-disk-utility. 

Hope it helps

**Comment by geckolinux** [comment]
Hi there, thanks for the additional documentation.

Unfortunately there is no utility like what you mention for openSUSE. If there was then GeckoLinux probably wouldn't exist! :-)

**Comment by DPinNM** [comment]
I just spent the past two days trying to update GeckoLinux Rolling with that 1700-file download and install. On my first try, I had a failure of the scripting at the end of the process (not unlike what Blaine [InfinitelyGalactic] experienced on YouTube). On my second attempt, happily, all went well. 

But now that I have that update, I'd like to "lock it in."  I'm not trying do a USB snapshot (a la MX Linux and PCLinuxOS) -- though that would be nice! -- since it's not possible.  But I see Timeshift is not available in YaST Software and is only a Community effort on software.opensuse.org (with the accompanying warning of certificates not being signed, etc, etc,).

Is there a consensus choice in the GeckoLinux/OpenSUSE user base for a Timeshift-like backup utility?
