### ISSUE TITLE
New Gecko Linux install, NVIDIA driver help please?

### ISSUE THREAD

**Issue by LittleCom** [geckolinux/geckolinux-project#139]
Hello,
I am a web designer and need Blender, FreeCAD, GIMP, OBS Studio and Shotcut for work.
Yesterday, I've tried and then installed Gecko Linux rolling XFCE and was impressed.
Unfortunately, I was not able to install the NVIDIA drivers and I was not able to find a tutorial that would document the steps.

My hardware is Linux friendly. Dell Inspiron 5680 with a NVIDIA 1070 GFX card.
The PC is almost 2 years old and has been running Arch-based distros flawlessly. 

Could someone point me in the right direction on installing the NVIDIA drivers?
As soon as someone helps me solve this, I'll move to Gecko. - LC

P.S. If I enable the NVIDIA repository and chose the second option 250 driver version, it installs but upon rebooting, my max res is 800 x 600 instead of 3440 x 1440.
On a new install, I tried to follow: https://en.opensuse.org/SDB:NVIDIA_drivers which produced the same results. Unusable monitor resolution.

**Comment by geckolinux** [comment]
Unfortunately I don't have any NVIDIA hardware to test, and therefore I have no experience or suggestions for you. I watched this review on Youtube (in Polish) where the reviewer had installed the Nvidia drivers and they appeared to have "just worked". Here's the reply to my question about that:

https://www.youtube.com/watch?v=kuOBO9gxJ_w&lc=UgzO2dw6kUVSX8B_arN4AaABAg.9BfPy4rRKMD9BhXTkClj4f
> Nvidia - i just searched for drivers in repo and install it, it just works :)

Could you please try one of the STATIC versions to see if that works better?

Also I wonder if this applies to your setup?
https://en.opensuse.org/SDB:NVIDIA_drivers#Secureboot

**Comment by LittleCom** [comment]
Thank you for responding.
Amazingly, I did follow the link you suggested (https://en.opensuse.org/SDB:NVIDIA_drivers#Secureboot) and after that, gave up.
Just watched a bit of the YouTube video (around the 7.5 minute mark) and noticed that he has older hardware as the 390 driver series seem to be installed. 

It's really too bad because if it weren't for this one issue, I'd gladly move to Gecko Linux in a heartbeat. Gecko looks sharp and my first impressions were 110%.  

I don't know about the static version. Coming from Arch, it's a step back and rolling would be preferred. 
I will still install it on my laptop which doesn't need the proprietary NVIDIA drivers but it would be better to have both machines run the same Linux flavor.

**Comment by geckolinux** [comment]
> I don't know about the static version. Coming from Arch, it's a step back and rolling would be preferred.

I understand, but just for testing purposes it would be very helpful to me to know if it works in STATIC but not under ROLLING. If that were the case it could be a matter of a missing package or something minor that has changed in the slightly newer Tumbleweed base that I could tweak to make it work.

Another thing, did you try completely updating the system first (or later I suppose) with `sudo zypper dup` ? I know that the NVIDIA drivers are highly dependent on the kernel version and probably some other dependency package versions, and Tumbleweed rolls very fast.

**Comment by LittleCom** [comment]
Change of plan ... 
I just installed as per your recommendation and will know shortly if NVIDIA can be installed.
What I just noticed and LOVED about gecko is that when I move a windows from an ultrawide 1440p display to a 4k monitor, the UI scales which is a first. AMAZING (from a person that is not often amazed). :)  NICE job!

Update!
I just tried to add the NVIDIA repo and saw that (using static), the NVIDIA driver 450.57 is already installed! YAY :)

**Comment by geckolinux** [comment]
I'm glad GeckoLinux is generally working well for you, that's great to hear.

> I just tried to add the NVIDIA repo and saw that (using static), the NVIDIA driver 450.57 is already installed!

Already installed or available for installation out of the box? This is the repo that is included with GeckoLinux STATIC (but no packages are pre-installed):
https://download.nvidia.com/opensuse/leap/15.2/

So do I understand correctly that with GeckoLinux STATIC the preconfigured NVIDIA repo offers a driver that works correctly with your hardware?

**Comment by LittleCom** [comment]
I spoke to early.
Loading the YaST Software tool showed a white check box, checked with the 450.x NVIDIA driver present. 
I then clicked that checkbox, and accepted the install which did what I expected it to do. After installing all of the dependencies, I rebooted hoping that the STATIC version could load up with the proprietary video driver but just like before, the boot screen showd lots of error messages (which flew by too fast to read) and upon logging in, I got the same 800 x 600 display size. 

So ....
Gecko is perhaps the best Linux distro right now but professionals who need the latest software (which only Thumbleweed offers), Arch-based distros are a must. There are many things I love like the UI scaling when moving content from one monitor to another but in the end, the display is where Linux starts and ends. 
Thankfully, the genius Timeshift utility enables us to experiment with distros like Geko but after 24 hours of trying and multiple installs, it's time to get my system back to a working state. I'll keep an eye on your work and as soon as the NVIDIA issue is under control, I'll give Gecko Linux another try. 
Thanks for helping me. - LC

**Comment by geckolinux** [comment]
Thanks for confirming. I'd appreciate it if somebody who is familiar with the particularities of NVIDIA could please give me some tips on what is missing in GeckoLinux to make it support NVIDIA correctly. Or is broken most of the time in openSUSE as well?

**Comment by geckolinux** [comment]
If you have more time some other day to play around a little more, I would be very interested to know what happens if you try installing openSUSE Tumbleweed proper and then test the NVIDIA drivers with that.

**Comment by geckolinux** [comment]
@LittleCom  If you have more time some other day to play around a little more, I would be very interested to know what happens if you try installing openSUSE Tumbleweed proper and then test the NVIDIA drivers with that.

**Comment by geckolinux** [comment]
https://github.com/geckolinux/geckolinux-project/issues/140

**Comment by LittleCom** [comment]
Hello again,
yes, I'd be happy to help because of the huge potential GeckoLinux has. Your version of OpenSuse is quite amazing and if it weren't for the NVIDIA issue, I would have switched my computers over to Gecko this (long) weekend. 

To others reading this,
If you are looking for something different from the "usual" then Gecko can be it. The moment I installed Gecko it felt like my "next distro". So far, I haven't seen anyone doing UI scaling when moving content between monitors and there are many other things that just feel "right".

**Comment by geckolinux** [comment]
Hi @LittleCom  Thanks a lot, I really appreciate the recommendation, and I hope that with a little more testing and troubleshooting we can make your NVIDIA hardware work out of the box. Please keep an eye on #140 . Also I think I'm going to re-open this bug (sorry for going back and forth) and refer more knowledgeable users than myself back to your issue here to see if they can help you troubleshoot it.

I still think that a good way to troubleshoot your problem whenever you have some spare time would be to install openSUSE proper and test to see if the NVIDIA drivers work on your hardware with that. Because if it doesn't work on vanilla openSUSE then it definitely won't work with GeckoLinux either, at least for the moment. But if it works there but not on GeckoLinux then it's just a matter of tweaking the default GeckoLinux configuration a bit.

**Comment by geckolinux** [comment]
From #140 :

> As for #139 , from the hardware perspective it is the ideal setup for suse-prime ( intel - nvidia ) combo. Normally doing the same steps as i did and setting suse-prime to nvidia should solve the issue.
> My previous laptop was an optimus that was a lot more hassle than this so i knew about prime, i am guessing that since his computer is a desktop most other distros default to the dGPU but somehow SUSE defaults to the iGPU ( think desktop intel chips have the same integrated graphics as mobile ones) and that might account for the resolution.
> 
> TBH, to help him a bit more we would need the errors that "flew by" on bootup.

**Comment by LittleCom** [comment]
Just to be clear abut the specs.
The PC I tried to install GeckoLinux on is a stock Dell Inspiron 5680 which has a 256 Gig SSD, 16 Gig of RAM, 8 Gig Nvidia GTX 1070 on a dell proprietary main board. 
The computer is almost 2 years old and run Linux since day one. Secure boot is off and almost all Linux distros run well on that hardware. 

**Monitors**
The PC has two monitors which are connected via display port. 
Monitor 1 is a 34" ultrawide which I do most of my work on.
Monitor 2 is a 28" 4K model which is usually off unless I need it for large projects. 

I will try and install GeckoLinux XFCE Rolling on my MSI laptop tonight. 
Right now, the laptop runs Manjaro which only works because I have permanently disabled the laptop screen. I kind of hope that I could transition to GeckoLinux for both machines eventually.
Last but not least, I also have an iMac which is networked to the Linux machines to share large audio and video files. 

I will report back if I can successfully install GeckoLinux on the 7-year-old MSI optimus laptop which has a K2000m GFX chip and connects to an external 32" 4K monitor. 

My disadvantage is that I am not familiar with the "SUSE way of system administration". Things would be better if I were but I'm sure that soon I will be. :)

**MSI Laptop Update**
OK, GeckoLinux on the MSI laptop is a no go because of the external monitor. After enabling it, the mouse cursor moves on that display but nothing else. I don't get a background and no windows can be dragged to the external monitor. 
Because of that, in actual install is too risky. If it weren't for the external monitor issue, I'd be installing GeckoLinux on that laptop right now because everything else works amazingly well.

**Comment by LittleCom** [comment]
for the last 24 hours, I've read and watched everything I could and now I will reinstall GeckoLinux once more.  
I will then learn and use snapshots so that I can undo a failed attempt of installing the NVIDIA drivers.
All of my work gets updated and saved to external drives or servers which means that if worse comes to worse, I am out an hour.

Hopefully, the NVIDIA issue will be resolved soon.
I am tired of not being able to shut down Manjaro unless I do it from the command line and Equally tired of my work computer's funky implementation of Timeshift which fills up my backup drive because it no longer overwrites old backups.

Hopefully, OpenSuse/GeckoLinux will fix my headaches. I feel optimistic.
So that's it for me. I'll keep reading the forum to learn more and everything else .... is history. 

**Thanks again for making GeckoLinux!** 
(If you were willing to re-brand to Geck**os**Linux I'd make you a cool free logo)  

Farewell, adieu, auf wiedersehen, goodbye! L C

**Comment by geckolinux** [comment]
I'm guessing that this is most likely an upstream issue:
https://www.reddit.com/r/openSUSE/comments/i6hs6t/nvidia_drivers_broken_on_leap_152_currently/

**Comment by esteelpaz** [comment]
@LittleCom @geckolinux 

Saw this link over on the "request for Nvidia data" as I posted there, I will post here as well.  I have three machines with Nvidia cards of various ilk, the latest being a '20 Sys76 linux computer.  I have several different TW and Gecko Rolling installs on them and in the disappearing longish past I used the proprietary Nvidia drivers, but then eventually took them out because essentially Nvidia doesn't keep pace with the fast development in the rolling distros.

I posted an issue about it on the Nvidia "linux" forum, and that is what the tech there told me.  And same problem if the card is getting "older" then they won't "go back in ancient time and fix it" . . . .

So, I like the hardware, but I use the nouveau driver and for the most part it does well.  On my '12 MacPro I have a TW install that I didn't use nouveau, but went "default" and it uses another video driver, and the graphics are "crispy" there as well.

Possibly there might be some overlaps on display resolution, where in one app they are set low, and in another they aren't . . . you might have to coordinate them??  Switching over from Arch to OpenSUSE there are some differences to learn, but I would say that indeed Gecko gives the best introduction to the joys of OpenSUSE.  I would suggest that you try to play with using nouveau, but if for some reason you can't I know that I have had proprietary Nvidia drivers installed in just about all of the linux OSs I have used, but really isn't a great interaction.  I'm sure you could find instructions for how to install Nvidia on the OpenSUSE wiki or forum.  It isn't that hard working through Yast, Packman repo is  needed, but Gecko has that and then something else has to be checked and boom, "nvidia" is added to the sources.list.

I don't recommend it if you need the latest software that rolling provides, for instance on my Sys76 laptop that had Pop!OS 21.04 there latest iteration, it has nvidia graphics built in to the system, and like all of my Nvidia linux installs it too started having problems with "suspending" and reviving from suspend, and then the keyboard wouldn't work when reviving . . . I wanted to remove nvidia but I couldn't . . . it's in the shop under warranty right now because Nvidia is intertwined in their system. <sad face.>

**Comment by geckolinux** [comment]
@esteelpaz 
> So, I like the hardware, but I use the nouveau driver and for the most part it does well. On my '12 MacPro I have a TW install that I didn't use nouveau, but went "default" and it uses another video driver, and the graphics are "crispy" there as well.

Interesting, thanks for the report. And what about thermal performance with nouveau?

**Comment by esteelpaz** [comment]
@geckolinux:

My pleasure . . . I did post this previously on your request for Nvidia
data thread . . . .  It seems to do OK with "thermals" . . . .  : - ))  How
would I show that data??? that wouldn't be "subjective"???

**Comment by geckolinux** [comment]
@esteelpaz Yep, definitely subjective. If the the laptop doesnt' feel and/or smell like it's burning up that's good. My only experience with NVIDIA is with an extremely old Toshiba laptop with an ancient card that is no longer supported. But with nouveau it would just burn up, whereas with the proprietary driver it was much cooler.

**Comment by esteelpaz** [comment]
@geckolinux:

Ah, the "overtly obvious" . . . flames, etc.  Nope, nothing like that.
Back in the PPC days of Apple computing we had to use some old driver,
can't think of the name, but we all were wishing we could use nouveau . . .
this was '07 or so . . . .  Linux has come a long way since then, and so
far nouveau is the best option to use with Nvidia hardware when moving with
the fast lane linux distros . . . .

**Comment by esteelpaz** [comment]
Following up, I'm booted up in a several month old Gecko Plasma Rolling
install on my '12 MacPro with a non-stock Nvidia card (oldish card) . . .
"Nvidia" is showing in the repos, even though I didn't request it, it added
itself, but lsmod shows "nouveau" . . . .

I'm not doing anything too processor intensive but feeling the side of the
machine it feels "thermally neutral" . . . .

**Comment by geckolinux** [comment]
> "Nvidia" is showing in the repos, even though I didn't request it, it added itself

Nope, I added it to the default package repos. ;-) It's available for installation out of the box with GeckoLinux, but not pre-installed.

**Comment by esteelpaz** [comment]
> > "Nvidia" is showing in the repos, even though I didn't request it, it added itself
> 
> Nope, I added it to the default package repos. ;-) It's available for installation out of the box with GeckoLinux, but not pre-installed.

@geckolinux 

"You" being "it" . . . the Gecko system obviously has "Nvidia" already in the repos, whereas over in TW it's a "process" that has to be undergone . . . .  In Gecko, it's available . . . .  

Also, checking the Display in Settings in Plasma, on an old square View Sonic display, resolution is on the top setting "1280 X 1024 (5:4)" . . . I didn't request that either, it "added itself" . . . . : - )))))

**Comment by RolandHughes** [comment]
> Hello, I am a web designer and need Blender, FreeCAD, GIMP, OBS Studio and Shotcut for work. Yesterday, I've tried and then installed Gecko Linux rolling XFCE and was impressed. Unfortunately, I was not able to install the NVIDIA drivers and I was not able to find a tutorial that would document the steps.
> 
> My hardware is Linux friendly. Dell Inspiron 5680 with a NVIDIA 1070 GFX card. The PC is almost 2 years old and has been running Arch-based distros flawlessly.
> 
> Could someone point me in the right direction on installing the NVIDIA drivers? As soon as someone helps me solve this, I'll move to Gecko. - LC
> 
> P.S. If I enable the NVIDIA repository and chose the second option 250 driver version, it installs but upon rebooting, my max res is 800 x 600 instead of 3440 x 1440. On a new install, I tried to follow: https://en.opensuse.org/SDB:NVIDIA_drivers which produced the same results. Unusable monitor resolution.

Here is [a Gecko Linux/NVidia journey](https://www.logikalsolutions.com/wordpress/information-technology/gecko-linux-nvidia-and-boinc/) for the GT 630 that needs the G05 drivers. The process should help others.

As always with RPM based distros NVidia support is wanting.

**Comment by RolandHughes** [comment]
> for the last 24 hours, I've read and watched everything I could and now I will reinstall GeckoLinux once more. I will then learn and use snapshots so that I can undo a failed attempt of installing the NVIDIA drivers. All of my work gets updated and saved to external drives or servers which means that if worse comes to worse, I am out an hour.
> 
> Hopefully, the NVIDIA issue will be resolved soon. I am tired of not being able to shut down Manjaro unless I do it from the command line and Equally tired of my work computer's funky implementation of Timeshift which fills up my backup drive because it no longer overwrites old backups.
> 
> Hopefully, OpenSuse/GeckoLinux will fix my headaches. I feel optimistic. So that's it for me. I'll keep reading the forum to learn more and everything else .... is history.
> 
> **Thanks again for making GeckoLinux!** (If you were willing to re-brand to Geck**os**Linux I'd make you a cool free logo)
> 
> Farewell, adieu, auf wiedersehen, goodbye! L C

As a general rule RPM has never bothered to test NVidia. All of the RPM based distros point the finger at NVidial and wail it is all their fault. Debian based distros have no problem with NVidia. Even when you get NVidia drivers to "work" with RPM based distros, they don't really work.

[Gecko Linux/BOINC/NVidia journey](https://www.logikalsolutions.com/wordpress/information-technology/gecko-linux-nvidia-and-boinc/)

As you can see when you read that (even should be able to follow all the steps) getting NVidia to "work" on the desktop as far as the NVidia X Server Settings screen says, still has the warning about lack of acceleration and BOINC cannot identify any valid CUDA source. That same card in two other machines running Debian based distros using the same 470 driver work flawlessly with BOINC. This very machine had Linux Lite using the same version of the driver and BOINC worked flawlessly. I needed to test some software on an RPM based distro so I sacrificed this machine. Between tests I let my spare testing machines run BOINC.

RPM is always so painful.

**Comment by esteelpaz** [comment]
@RolandHughes 

Just more or less repeating what I posted previously in this thread, that in "rolling" editions Nvidia doesn't really keep pace, so in my machines that all have Nvidia hardware, I use "default" or "nouveau" drivers and, it is "fine."  My needs are not very demanding . . . .  But, as geckolinux mentioned, possibly going to "static" edition might help to get Nvidia drivers working?? 

Gecko comes with the Nvidia repos installed, so in theory it should be easier to get proprietary going, but in all of my rolling distros I don't waste time with them, because they "break" with kernel upgrades and so forth . . . .

Best option, try out "multi-booting" on your machine . . . as I do . . . when you need to work, boot into the system that runs Nvidia, but for daily driving, click into Gecko rolling . . . ??  Variety is the spice of life, etc.
