### ISSUE TITLE
Missing Repository

### ISSUE THREAD

**Issue by fixer1234** [geckolinux/geckolinux-project#14]
I just came across Gecko and am kicking the tires.  I loaded it yesterday and have tried over the last two days to update the packages with YaST.  

One of the included "unofficial sources" is Buumi KSuperKey, which appears to possibly be an orphan.  Ksuperkey appears in the Lost and Found section of the application menu.  Every time I run YaST software management, a message pops up that it can't access this particular repository (and trying to go directly to that repository link produces Error 404 Object not found).

Is this something for which support was dropped after building it into the live DVD, or has the repository moved or something?  What should I do with this to clean it up?

**Comment by geckolinux** [comment]
Hi there, what is the exact name and version of the ISO you installed from?

**Comment by fixer1234** [comment]
What I copied to the DVD label  is Geckolinux Plasma Stable x86-64 421.160627.0.  I did a little exploration, and it looks like Buumi has moved on to Leap 42.2.  The 42.1 repository doesn't seem to exist but 42.2 is there.  Leap 42.2 is based on a different kernel, so it isn't clear whether what's in the new repository is compatible or has been tested.

**Comment by geckolinux** [comment]
Thanks for the additional information. It looks like you're right, Buumi eliminated his Leap 42.1 repo. The KSuperkey is simply installed to map the Windows key to the Plasma start menu. I would recommend leaving it installed if you want that functionality, and simply deleting the Buumi repository from your sources so that it stops bugging you. It will no longer be necessary if/when you upgrade to 42.2, because Plasma 5.8 finally includes this functionality out of the box.

I'll try to update the GeckoLinux _Static_ ISOs as soon as possible, but SuseStudio is down at the moment and I don't have access.
