### ISSUE TITLE
Help wanted: Users with NVIDIA hardware please test and troubleshoot

### ISSUE THREAD

**Issue by geckolinux** [geckolinux/geckolinux-project#140]
Hi everyone, I'd like to request your help testing the latest GeckoLinux releases with NVIDIA hardware. I don't own any NVIDIA devices, and therefore I can't test how well the included upstream NVIDIA repository works with GeckoLinux. It would be very helpful if users could test the proprietary NVIDIA drivers and report here whether it worked or not. And if it didn't work, I would also appreciate your suggestions and tips as to _why_ it didn't work and how NVIDIA could be properly supported under GeckoLinux. Also, if it doesn't work with your hardware, it would be helpful to know if it does or doesn't work on that same hardware with an installation of vanilla openSUSE. Thanks in advance!

**Comment by sorinfatu** [comment]
Hello,
While searching for support for my laptop i ended up here and figured i might as well try gecko and see if i can get the nvidia card to work.
Went for the KDE rolling option. Hardware is a Ryzen 7 3750H with Vega 10 graphics and a GTX 1650 (not a very popular combination in the linux world yet and just starting get some more support)

After a fresh install the system booted fine to desktop with the correct resolution (1920x1080 - built in screen) - obviously using the vega gpu
Did a zypper dup, rebooted, opened yast software, somehow there were 4 updates there, one related to ucode for amd and a couple of drivers for xf86 amd. Rebooted again.

Installed nvidia drivers from the nvidia repo that is already added - in my case it was the G05 so 450 version of the driver. Rebooted again and nvidia settings was working and showing info.
At this point the gpu used was still the vega one, so to get this working on the nvidia one only i had to install suse-prime.
Something that is not obvious but the commands to use suse-prime are not visible to the user - must be run via sudo or one can install the suse-prime kde widget from the repos.

Small caveat when it comes to suse-prime : while it is possible to set the nvidia gpu as the active one, it is not possible to return to the amd one from the widget or with the option "intel" - the workaround for this is to return to amd graphics via terminal using "sudo suse-prime unset"

If all that is needed is a hybrid mode, this works "out of the box" (in a way) just after installing the nvidia drivers and rebooting. As mentioned, nvidia settings is working at that point, showing information about the card and to start applications using the nvidia card one can use `__NV_PRIME_RENDER_OFFLOAD=1 <application>` for vulkan apps or `__NV_PRIME_RENDER_OFFLOAD=1 __GLX_VENDOR_LIBRARY_NAME=nvidia <application>` for glx apps

Issues:
- in hybrid mode extrenal monitors connected to hdmi ports that are in turn connected to the nvidia card will not work - they work fine in nvidia mode - this is general as of yet.
- minor screen tearing - somewhat mitigated by https://en.opensuse.org/SDB:NVIDIA_SUSE_Prime#Tearing_problem

**Comment by geckolinux** [comment]
Thanks @sorinfatu, that's extremely helpful! So, in summary, we could say that GeckoLinux ROLLING offers the same level of NVIDIA support and functionality on your hardware as openSUSE Tumbleweed after installing the proprietary driver and `suse-prime`?

Regarding `suse-prime`, I remember a few years back when I looked into NVIDIA hardware a bit more there appeared to be a proprietary Ubuntu solution, some kind of an NVIDIA GUI manager tool that offered a different (better) way of switching between discreet and integrated graphics. I don't remember what it was called, or if it even still applies in 2020?

Also, would you have any tips for #139 ?

Thanks again for your help.

**Comment by sorinfatu** [comment]
As far as i can tell, nothing that i did is specific to Gecko since the repos used are the same as the ones i would use on Tumbleweed - so yes, support and functionality is the same.

For `suse-prime` there is a graphical tool to switch gpu, it's `plasma5-applet-suse-prime` (at least on KDE) - however, `suse-prime` seems to be designed specifically for switching intel iGPU to nvidia dGPU and back. In my case the switch needs to happen between AMD iGPU and nvidia dGPU.
Probably some tweaking to `suse-prime` could solve the issue. something in the lines of porting the tool that POP OS uses https://github.com/pop-os/system76-power - but this is nothing specific to Gecko but to the entire openSUSE ecosystem - guessing that until these hardware combinations get more popular it won't be fixed. The hybrid mode working is enough for me as it allows some on-demand graphics and i can always alias those commands to have them working better.

As for https://github.com/geckolinux/geckolinux-project/issues/139 , from the hardware perspective it is the ideal setup for `suse-prime` ( intel - nvidia ) combo. Normally doing the same steps as i did and setting `suse-prime` to nvidia should solve the issue.
My previous laptop was an optimus that was a lot more hassle than this so i knew about `prime`, i am guessing that since his computer is a desktop most other distros default to the dGPU but somehow SUSE defaults to the iGPU ( think desktop intel chips have the same integrated graphics as mobile ones) and that might account for the resolution.

TBH, to help him a bit more we would need the errors that "flew by" on bootup.

**Comment by donuts12** [comment]
Sorry for the late replies, I hop around a lot. I will be retesting this again in Plasma Tumbleweed version. I did all my installs through Yast by installing all the intel packages. ( was 4 available when everything was installed in the beginning) Then installed nvidia G05 which selected all the packages and dependencies same procedure on tumbleweed. Suse-prime is automatically selected when installing G05 then in terminal I ran sudo prime-select intel which allows everything to run in a hybrid way in prime render offloading. I do not use optimus manager or anything like that. My intel cpu is i7 5700hq and my Nvidia GPU is a 970M. I will see if my logs will pick anything up when my nvidia-settings crashes again. 

Also another side issue that I did find in Suse was Firefox still ignoring the first mouse wheel scrolling event in X11 KDE, you can find it here https://gitlab.gnome.org/GNOME/gtk/-/issues/558 and here https://bugzilla.redhat.com/show_bug.cgi?id=1601046 this is mostly just for the Firefox RPM package that comes preinstalled from Yast and never was fixed. Works fine in Pop OS, Flathub, and Arch. I use X11 for my Intel/Nvidia GPU.

**Comment by geckolinux** [comment]
Hi @sorinfatu , thanks a lot for the very helpful details!

And thanks also to @donuts12 for the report! So does NVIDIA Settings crash every time, or just randomly? And do I understand correctly that the actual NVIDIA driver does work correctly with GeckoLinux on your hardware? Regarding the Firefox bug, I'm sure openSUSE will fix it eventually, they're usually a bit slow to update Firefox, even in Tumbleweed. GeckoLinux will never offer different packages or fixes to packages, because it's meant to be 100% upstream dependent, I only modify the configuration files and package selection (a lot).

**Comment by ElliotLurie** [comment]
> Hi @sorinfatu , thanks a lot for the very helpful details!
> 
> And thanks also to @donuts12 for the report! So does NVIDIA Settings crash every time, or just randomly? And do I understand correctly that the actual NVIDIA driver does work correctly with GeckoLinux on your hardware? Regarding the Firefox bug, I'm sure openSUSE will fix it eventually, they're usually a bit slow to update Firefox, even in Tumbleweed. GeckoLinux will never offer different packages or fixes to packages, because it's meant to be 100% upstream dependent, I only modify the configuration files and package selection (a lot).

I fixed NVIDIA settings by instaling `nvidia-glG05` from the repos. I guess someone will have to request that to be a dependency of the driver or something to fix that problem by default. You could also add the drivers to the ISO and do some hardware detection during the install or something. I'm glad to help with that!

**Comment by geckolinux** [comment]
@CheeseEBoi Great, thanks for the report! So the core driver functionality works well on your hardware? What model of NVIDIA? And is this with ROLLING or STATIC?

**Comment by ElliotLurie** [comment]
> @CheeseEBoi Great, thanks for the report! So the core driver functionality works well on your hardware? What model of NVIDIA? And is this with ROLLING or STATIC?

I'm running STATIC with the Dell XPS 9570 with a GTX 1050 ti. Other than having to run `prime-select intel/nvidia` in order to get things working initially, it works pretty well. Having to edit `.desktop` files still sucks, but with newer versions of desktop environments probably arriving in the future it isn't much of a problem.

Side note: I created a script based on that of Manjaro that makes it so you don't need to use `env __NV_PRIME_RENDER_OFFLOAD=1 __GLX_VENDOR_LIBRARY_NAME=nvidia <application>` in a `.desktop` file (to get the environment variables working). It literally just contains the following line:
```
__NV_PRIME_RENDER_OFFLOAD=1 __GLX_VENDOR_LIBRARY_NAME=nvidia $@
```
Save that as `/usr/local/bin/prime-run` or something, and put it in front of any command and it should work, `.desktop` file or not. So the command would then be `prime-run <application>`.
Probably not very important, but it saves time and makes things simpler.

**Comment by geckolinux** [comment]
Here's another one, if somebody more knowledgeable could offer him some tips: https://github.com/geckolinux/geckolinux-project/issues/145

**Comment by commonquail** [comment]
I can offer a slightly different perspective with the same conclusion; "works as upstream (probably)":

I have a desktop with a single GPU and all around recent hardware that I installed GeckoLinux_NEXT_Plasma.x86_64-152.200726.0.iso on. I [couldn't start the graphical installer](https://doc.opensuse.org/documentation/leap/startup/single-html/book.opensuse.startup/index.html#sec-installation-troubleshooting-graph) before adding `nomodeset` (and [UEFI machines don't get the boot menu with convenient alternative boot override shortcuts](https://doc.opensuse.org/documentation/leap/startup/single-html/book.opensuse.startup/index.html#sec-boot-parameters-uefi)) but afterwards installation completed without further incident<sup>1</sup>.

I installed `x11-video-nvidiaG05` per [the instructions](https://en.opensuse.org/SDB:NVIDIA_drivers), rebooted, got the MOK import, and no longer needed `nomodeset`. At this point the driver seemed to work: I hadn't had a single crash or obstruction beyond the initial `nomodeset`. However, the displays felt sluggish and unresponsive, and video games I had played without incident the week before ran at single-digit FPS.

I don't recall what made me suspect that I might in fact be using software rendering despite the driver recognizing my GPU -- it might have been that the fans didn't seem to turn on anymore. When I did, I found and installed `nvidia-glG05` (which installed a few other, related dependencies), rebooted, and since then everything has worked fine (and the completely insufferable fans started running again...). I was aware of this thread beforehand but since I hadn't had any crashes I didn't make the connection to CheeseEBoi's reply.

It definitely seems like either the SDB article is incomplete or the `nvidia-glG05` should have been a dependency of the `x11-video-nvidiaG05` package. I wanted to adjust the article accordingly but the Wiki's new user management system is broken with respect to creating new users...

---

<sup>1</sup> Well, that's technically untrue. I really wanted to use LVM partitions and managed to create them with the live image, but while Calamares would display my volume group it wouldn't recognize existing volumes, crashed whenever I selected the volume group, and wouldn't let me proceed with installation. In the end I skipped LVM. Calamares' historically lacklustre support for LVM is well documented on the Internet but the consensus now seems to be that it should work. This surely has nothing to do with NVIDIA, though.

**Comment by geckolinux** [comment]
@commonquail Thanks very much for the very useful report.

**Comment by geckolinux** [comment]
Reopening this issue due to #243 .

**Comment by esteelpaz** [comment]
@geckolinux 

I'm just seeing this thread now, I have "nvidia" cards in three machines that I'm running, but for the most part I use "nouveau" as the driver, because the proprietary "nvidia" drivers often don't keep up with the system upgrades, and it creates "problems."

I did a recent install of Gecko Plasma rolling to my '12 cMP and I don't recall making a decision on the graphics driver, as I was able to do in my TW install (there I did default as the choice, which isn't nouveau) and I'm booted in the Gecko right now and lsmod shows "nouveau" for video.  I am "OK" with that choice for running my video . . . renders just fine.  I got into a mini-nightmare in my Sys76 having issues with not "waking" from sleep in the OEM "Pop!_OS" install . . . tech support suggested "purging nnvidia" which I did do in a Siduction install w/o issue, but apparently in Pop! the nvidia drivers are "welded" into the system . . . total snafu . . . corrupted the system, there it took ME awhile to figure out how to get the GUI back working--and now I'm running "hybrid" graphics, which is mainly mobo card with ability to "go nvidia" . . . .

I have a Gecko install on that computer . . . I could check which driver is being used there tomorrow, largely if I can avoid using proprietary drivers I do, because for rolling or beta they aren't keeping pace.

**Comment by memesforlife1** [comment]
@geckolinux 
Nvidia drivers on my optimus laptop are great! And has the best performance compared to all the other linux distos I've used, although I've only used it for minecraft, and the perfomance is about the same as Vanila Tumbleweed

**Comment by geckolinux** [comment]
@memesforlife1  Thanks for confirming!

**Comment by memesforlife1** [comment]
> Thanks @sorinfatu, that's extremely helpful! So, in summary, we could say that GeckoLinux ROLLING offers the same level of NVIDIA support and functionality on your hardware as openSUSE Tumbleweed after installing the proprietary driver and `suse-prime`?
> 
> Regarding `suse-prime`, I remember a few years back when I looked into NVIDIA hardware a bit more there appeared to be a proprietary Ubuntu solution, some kind of an NVIDIA GUI manager tool that offered a different (better) way of switching between discreet and integrated graphics. I don't remember what it was called, or if it even still applies in 2020?
> 
> Also, would you have any tips for #139 ?
> 
> Thanks again for your help.

I don't know about outher DEs but on gnome you install a extention with yast with the Gnome:Apps Repo for Opensuse Factory/TW called `gnome-shell-suseprime-switcher`
