### ISSUE TITLE
Recognition of GeckoLinux on the openSUSE Leap 15.2 release retrospective

### ISSUE THREAD

**Issue by lkocman** [geckolinux/geckolinux-project#152]
Hello GeckoLinux

this is a heads up that you have received an appraisal as part of the openSUSE Leap 15.2 retrospective https://en.opensuse.org/Portal:15.2/Retrospective

Please consider this resolved once you read the comment.

**Comment by geckolinux** [comment]
Hi @lkocman , thanks very much for the kind gesture! I'm really glad that the openSUSE devs see GeckoLinux for what is is-- I'm not attempting to steal openSUSE users, but rather offer something different for those who probably wouldn't otherwise use openSUSE. And I'm always proud to say that GeckoLinux is unapologetically openSUSE at its core, and I recognize that I'm standing on the shoulders of giants in the openSUSE community. Thanks again!
