### ISSUE TITLE
Cannot install GNOME Applications Menu Extension

### ISSUE THREAD

**Issue by anselal** [geckolinux/geckolinux-project#19]
I try to install the application menu extension from https://extensions.gnome.org/extension/6/applications-menu/ but it fails without any errors.

**Comment by geckolinux** [comment]
Hi there, you can check the gnome-tweak-tool extensions section to see if it shows any specific errors. Otherwise, please file a bug with the Gnome project, giving specific information about what version of Gnome you are running.

I'll close this bug, because GeckoLinux only offers a spin of openSUSE with Gnome, and I'm not a Gnome extension developer.

Thanks and best regards.

**Comment by anselal** [comment]
I had no problem installing this extension in openSUSE Leap 42.2.

**Comment by geckolinux** [comment]
OK, I looked farther down in the comments on that extension and found the following:

> will work with current opensuse tumbleweed with 3.20, needs these two dependencies installed `libgnome-menu-3-0` , `typelib-1_0-GMenu-3_0` credit to mrpollo from other extension comments.

I tried installing those packages, which fixed it. I'll include them by default in future GeckoLinux Gnome releases.

**Comment by anselal** [comment]
Thank you very much.
