### ISSUE TITLE
geckolinux is missing the NetworkManager-connection-editor package

### ISSUE THREAD

**Issue by EssamTarik** [geckolinux/geckolinux-project#25]
not that it's a huge issue , but
when i right click the network tray icon and select edit connections nothing happens , because the package is missing

p.s : tried on the mate and cinnamon version on geckolinux stable 422.161228

**Comment by geckolinux** [comment]
Hi there, thanks for reporting.

This issue is fixed in the Mate version, scheduled to be released today. (You can install `NetworkManager-connection-editor` to fix it.)

As for the Cinnamon version, there are two entries with redundant functionality. "Network Connections" won't work, but "Network Settings" will.
