### ISSUE TITLE
Unable to use FN Keys to adjust volume

### ISSUE THREAD

**Issue by geckolinux** [geckolinux/geckolinux-project#285]
### Discussed in https://github.com/geckolinux/geckolinux-project/discussions/284

<div type='discussions-op-text'>

<sup>Originally posted by **fbr15** September 28, 2021</sup>
I have an ASUS laptop (ASUS N56 series) and I want to adjust the volume by using the FN key and F10 (mute), F11 (vol down), F12 (vol up), but the FN keys doesn't work.
Before I was on open suse leap and adding "acpi_osi= " in kernel parameters solved the problem, but in gecko next it doesn't work.
Any ideas are welcome, thanks </div>

**Comment by geckolinux** [comment]
Please re-test upcoming _ROLLING_ editions.

**Comment by franciscomilagres** [comment]
Hi there!

Same situation here! I came from OpenSUSE with KDE (and there the keys were working).

I have an Asus n53ta and both Fn+Key commands (e.g. mousepad control, volume control, sleep command) and Multimedia keys (those that are independent keys) are not working in Gecko Stable (I tried GNOME and KDE).

The only keys that work with Fn are the Bright control ones, and I think it is because BIOS listens these commands directly and responds independently from the system (these Bright keys also work in BIOS).

I also tried setting the keyboard model with YaST keyboard and didn't work to ASUS and each one of the 'Generic' options. Didn't work.
The detection during installation process sets it automatically to the Generic 105-key model.

I googled about solutions related to KDE, didn't work.
Initially I thought that it was a sound related problem and [these solutions](https://en.opensuse.org/SDB:Audio_troubleshooting) from OpenSUSE didn't work for me.
After installing GNOME Gecko I faced the same problem.

With OpenSUSE and Ubuntu the Fn keys work fine!

I also tried [this](https://venthur.de/2021-04-30-keychron-c1-on-linux.html), setting an fnmode parameter in a similar path to hid settings (the site's `/sys/` path got me to permission denied even with sudo).

I guess this problem is related to some WMI module. Some people use such an asus-wmi from github, but n53ta isn't mentioned there. I couldn't find any specific wmi packages from OpenSUSE software.
