### ISSUE TITLE
Budgie (possibly others too) is missing some user-friedly tool for updates.

### ISSUE THREAD

**Issue by Squeezer-CZ** [geckolinux/geckolinux-project#30]
Something like Ubuntu has. Some icon in panel, maybe popup, or something, that would tell user "hay, you need to update your software". If you want to have Geckolinux available to some less "geeky" users, it is really needed.

I am myself somehow new to opensuse (I am using Debian from young age) and I had kinda unexpected hard time to find out how to update via Yast. It is not much user friendly at first.

But do as you wish. :)

**Comment by geckolinux** [comment]
Hi there, I would also really like to have a friendly update tool, but 
none exist for openSUSE. Since I'm not a programmer, I can't really 
create any new software to do this. However, the process to update 
GeckoLinux via YaST, described in the wiki, is really quite easy:
https://github.com/geckolinux/geckolinux-project/wiki#how-to-update-geckolinux
