### ISSUE TITLE
Discover app icon - Restart

### ISSUE THREAD

**Issue by LinuxWOW** [geckolinux/geckolinux-project#301]
Hi geckolinux Team

Thanks for amazing OS, Its been wonderful. I have been on open-SUSE gecko for awhile now 6 months longer then most and i haven't got off its fast so rock solid. Not to many updates. 

I'm on geckolinux KDE Rolling the discover app icon has been coming up with crash every-time i restart. I would like it back working if i can get some help.  When i first installed gecklinux i remember it was working somewhere between i think updates or installing packeges somewhere cause discover icon to not come up anymore.?  This is the only issue i have been having everything else is good.

Lett me know if you need more info try my best send it.

**Comment by geckolinux** [comment]
Hi there, really glad that GeckoLinux is working well for you.

However, I don't recommend installing Discover or Gnome Software or anything else that uses the buggy and unmaintained PackageKit framework. These are the only update methods that GeckoLinux supports:
https://github.com/geckolinux/geckolinux-project/wiki#how-to-update-geckolinux

**Comment by LinuxWOW** [comment]
Discover is in KDE geckolinux when installed isn't it? i can't remember i installed it like 6 months. I like discover app store its part of KDE shouldn't be issue. Its nice GUI for updating packages why would you not want users to use it? It works fine just the discover icon app icon crashes help fix it

**Comment by LinuxWOW** [comment]
Sorry that's not what i'm referring too? The discover applet on KDE panel crashes every-time

**Comment by geckolinux** [comment]
Hi there, the entire KDE software management system with Discover and the panel updater applet all use an intermediate package management framework called PackageKit that interferes with the underlying `zypper` package management system that openSUSE uses, and it causes major problems, such as improper Tumbleweed package updates and preventing `zypper` and YaST from working:

https://www.reddit.com/r/openSUSE/comments/n3v2ie/this_is_why_i_dont_use_packagekit_gnome_software/

As such, Discover and anything else that pulls in PackageKit dependencies are not pre-installed on GeckoLinux and are not recommended for installation by the end user.

**Comment by LinuxWOW** [comment]
OK i do not agree with this decision. KDE discover is part of KDE PLASMA and nice GUI APP for new users.  even if not for new user. alot of people still use it. shouldn't be up to you to choose not to use it or not just to strip something out or say not to use it. Wren its in use still by dev's. in KDE

**Comment by geckolinux** [comment]
That's the beauty of Linux. It absolutely **_is_** up to the distributor to choose whether or not to include a given package by default, especially when there are very weighty reasons to not use it. But there's nothing stopping you from installing it if desired. It hasn't been "stripped out", but rather it was intentionally not included due to the major PackageKit issues that come along with it as I mentioned. If it doesn't work for you after you installed it then it's probably due to a misconfiguration or a missing package, and that's more proof that everything using PackageKit is overly-complex and prone to fail.

**Comment by LinuxWOW** [comment]
Its Discover Notifier that's crashing all the time on restart. How to fix

**Comment by geckolinux** [comment]
> Its Discover Notifier that's crashing all the time on restart. How to fix

Yes, that also uses the PackageKit backend. If you look at https://www.reddit.com/r/openSUSE you'll see two threads right next to each other about major problems with Discover, so it's probably not worth trying to fix.

**Comment by geckolinux** [comment]
Notice what this experienced maintainer on the openSUSE KDE team says about Discover and its tray updater widget:
https://www.reddit.com/r/openSUSE/comments/qlt5zi/tumbleweed_refuses_to_update/hj7huw5/
> It's supposed to do a `dup`, but PackageKit has some differences unfortunately.

So that makes at least 3 threads on /r/openSUSE in two days, all related to the chaos that PackageKit causes on vanilla openSUSE systems that include it by default.
- https://www.reddit.com/r/openSUSE/comments/qlt5zi/tumbleweed_refuses_to_update/hj7huw5/
- https://www.reddit.com/r/openSUSE/comments/qlcorw/how_can_i_fix_it_trying_to_update_via_discover/
- https://www.reddit.com/r/openSUSE/comments/ql716i/is_kde_discover_fixed_in_leap_1532_respin/

**Comment by geckolinux** [comment]
And here's another one:
https://www.reddit.com/r/openSUSE/comments/rajlvq/packagekit_is_blocking_zypper_how_to_fix_this/
