### ISSUE TITLE
Outdated releases?

### ISSUE THREAD

**Issue by K0-RR** [geckolinux/geckolinux-project#313]
All static releases are from June and Rolling ones are from May.
May I ask what is the reason for it? I know I can just upgrade it after installing but downloading half a year of packages will be slow. Looking at previous releases there weren't any gaps between for so long.

**Comment by geckolinux** [comment]
There are always large numbers of updates, even after a few weeks or months, so that's not really something that GeckoLinux can change unless it had weekly builds. And after installing it you'll still have a significant number of updates from the normal openSUSE update cadence, so a more recent GeckoLinux build would only only save you from one update cycle at best.  That's why GeckoLinux is only rebuilt when there are some significant changes or improvements that I want to ship with the default configuration.
