### ISSUE TITLE
System is unbootable after installation 

### ISSUE THREAD

**Issue by Neocamelus** [geckolinux/geckolinux-project#360]
Hello,

I wanted to install GeckoLinux MATE Rolling edition.
Unfortunately, the system cannot boot after installation.

I have the following message.

```
Loading Linux 5.16.0-1-default...
error: ../../grub-core/fs/fshelp.c:257:file /vmlinuz-5.16.0-1-default not found.
Loading initial ramdisk ...
error: ../../grub-core/loader/i386/linux.c:1053:you need to load the kernel first.
```

PS: The following partitioning worked with GeckoLinux Static. 

![HD](https://user-images.githubusercontent.com/12272459/155876334-541515b0-e934-4bbe-96e3-50292fb79f83.png)

**Comment by esteelpaz** [comment]
Commenting as fellow user of MATE Rolling . . . is this a multi-boot situation?  If so did you update your master grub bootloader so that it can find the new install??  Seems like some kind of "grub" problem?

I was just having an issue with Gecko Plasma where it was booting to a TTY and not making it to the GUI.  I just changed the display manager to gdm and that "fixed" the issue.  Do you have a copy of SuperGrub2 on a disk that you can use to try to boot your install?  If it boots from that, then it would show that it is a grub bootloader issue . . . .

**Comment by Neocamelus** [comment]
Thank you for all these ideas. But I must admit that the fact that the distribution is unusable after installation did not make me want to continue...

I tested AçorOS and SpiralLinux. The existing partitioning is accepted. I plan to continue with SpiralLinux, since the Leap edition risks being abandoned.

**Comment by geckolinux** [comment]
Thanks @Neocamelus , sorry I couldn't be of more help. I'm not exactly sure why that would happen specifically on your hardware or partition layout, I can't reproduce the bug with my testing and/or production setup. It's definitely not a common error, but I'm sure there must be some edge case that is triggering it. Would it be OK if I ping you when I generate the next set of GeckoLinux Rolling images so that you can give it a quick spin?

As for SpiralLinux, thanks for giving it a try, please let us know how that works.

**Comment by Neocamelus** [comment]
Hello @geckolinux, 

The bug is strange indeed.
It didn't happen with older versions.
I would gladly test the next ISOs.

And a big thank you for SpiralLinux which works very well.

**Comment by esteelpaz** [comment]
@geckolinux 

Sometimes there is an error during an installation, and then "trying it again" often times will run through properly . . . .

Two things, as mentioned before, it appears like grub isn't finding the kernel . . . so the question is why?  Second issue, which may or may not have any bearing, boot partition was formatted as ext2, rather than the more standard fat32????

**Comment by Neocamelus** [comment]
The bug did not recur with new ISOs.
Thanks to you two.

**Comment by esteelpaz** [comment]
@Neocamelus 

cool.  sometimes things just "autocorrect" back into normalcy???

**Comment by geckolinux** [comment]
Excellent, thanks a lot for confirming!
