### ISSUE TITLE
Mate Tweak asks for a password

### ISSUE THREAD

**Issue by Neocamelus** [geckolinux/geckolinux-project#361]
Hello, 

I installed GeckoLinux MATE static edition.
After modifying the panel settings in Mate Tweak, I am asked for a password.
The root password that works elsewhere doesn't work here.

Regard

![MATE Tweak](https://user-images.githubusercontent.com/12272459/155845300-2a7cb226-ee4a-4b65-af70-0cc709d5866f.png)
s

**Comment by geckolinux** [comment]
Thanks for the report, I confirm the bug. It's an upstream openSUSE bug, so GeckoLinux can't do anything about it. With that said, I tried Mate Tweak in the live system and it "works" because there's no root password, but it simply doesn't work well for changing the panel layout and it never has worked. So I'll remove Mate Tweaks from the next release.
