### ISSUE TITLE
Rolling and Static: Cinnamon Crashes when panel is set to intellihide

### ISSUE THREAD

**Issue by amethylghostling** [geckolinux/geckolinux-project#390]
Whenever I have used Gecko, I can't get cinnamon crashes to go away. Usually happen when I am opening an app or changing directories in the file manager.
In ~/.xsession-errors :
>(cinnamon:3494): Clutter-CRITICAL **: 22:12:14.864: clutter_actor_iter_next: assertion 'ri->age == ri->root->priv->age' failed

Please correct me if this error could not be causing this crash and point me on how I can reliably be able to find the specific error causing this crash. For that case here is my xsession-errors: https://drive.google.com/file/d/1Pev9c_g3alrFuvnwjWrOLXFbNh5XAXw_/view?usp=sharing.
I have tried my oldest and numerous other snapshots. Also has the problem. I have changed quite a few settings and have no applets, desklets or extensions installed.

**Comment by geckolinux** [comment]
Hi there, I occasionally see Cinnamon crashes as well. I don't think it can be fixed, at least not by me or openSUSE. Please report this to the Cinnamon upstream bug tracker.

**Comment by ghost** [comment]
> Hi there, I occasionally see Cinnamon crashes as well. I don't think it can be fixed, at least not by me or openSUSE. Please report this to the Cinnamon upstream bug tracker.

Are you sure? This might be happening due to user made changes?

**Comment by geckolinux** [comment]
To test that you can delete or rename your `~/.config/dconf/user` file, which will make it use the Cinnamon defaults.

**Comment by ghost** [comment]
> Hi there, I occasionally see Cinnamon crashes as well. I don't think it can be fixed, at least not by me or openSUSE. Please report this to the Cinnamon upstream bug tracker.

Can you please check the Rolling live USB or a installed virtual machine to see if there are any crashes when opening apps when panel is set to intellihide. If so, any idea on what's causing the crashes?

**Comment by ghost** [comment]
> To test that you can delete or rename your `~/.config/dconf/user` file, which will make it use the Cinnamon defaults.

Can I recover my configuration afterwards?

**Comment by geckolinux** [comment]
> Can you please check the Rolling live USB or a installed virtual machine to see if there are any crashes when opening apps when panel is set to intellihide. If so, any idea on what's causing the crashes?

Feel free to try that and report back here.

> > To test that you can delete or rename your `~/.config/dconf/user` file, which will make it use the Cinnamon defaults.

> Can I recover my configuration afterwards?

Yes, you can save the `user` file somewhere and then replace it when you're done testing.

**Comment by amethylghostling** [comment]
Can I recover my configuration afterwards?

**Comment by ghost** [comment]
> To test that you can delete or rename your ~/.config/dconf/user

Has happened 3 times in 5 minutes of testing normally with Cinnamon's defaults unchanged. But when I open an file that I don't have the permissions to read in mousepad (it gives a floating window saying that it cant read the file) and then I switch to any directory in my home twice, it happens immediately almost everytime.
This seems to be the error
>(cinnamon:1039): Clutter-CRITICAL **: 22:58:47.674: clutter_actor_iter_next: assertion 'ri->age == ri->root->priv->age' failed
Exception in thread Thread-2:
Traceback (most recent call last):
  File "/usr/lib64/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/usr/lib64/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/bin/cinnamon-launcher", line 78, in wait_for_process
    os.execvp(FALLBACK_COMMAND, (FALLBACK_COMMAND,) + FALLBACK_ARGS)
  File "/usr/lib64/python3.8/os.py", line 568, in execvp
    _execvpe(file, args)
  File "/usr/lib64/python3.8/os.py", line 610, in _execvpe
    raise last_exc
  File "/usr/lib64/python3.8/os.py", line 601, in _execvpe
    exec_func(fullname, *argrest)
FileNotFoundError: [Errno 2] No such file or directory
None: no process found
Cinnamon warning: Failed to load theme "Menta": Failed to find a valid file for theme Menta

**Comment by geckolinux** [comment]
Maybe you could try switching to the default Cinnamon theme to see if that makes any difference.

**Comment by amethylghostling** [comment]
>  To test that you can delete or rename your `~/.config/dconf/user` file, which will make it use the Cinnamon defaults.
With the unchanged defaults, it crashed 4 times in 5mins of normal testing. However, it crashed almost every time if I opened a file that I don't have permission to read in mousepad (it comes with a popup saying it can't read the file) and then change to any directory in my home twice (seems to happen in default config only)
These seem to be the errors:
>(cinnamon:1032): XApp-WARNING **: 00:29:59.595: Could not spawn StatusNotifier watcher (xapp-sn-watcher): Failed to execute child process “/usr/libexec/xapps/sn-watcher/xapp-sn-watcher” (No such file or directory)
Cjs-Message: 00:30:00.459: JS LOG: Unknown network device type, is 14
Cjs-Message: 00:30:00.467: JS LOG: Unknown network device type, is 30
cinnamon-session[753]: WARNING: t+16.60729s: Detected that screensaver has left the bus
cinnamon-session[753]: WARNING: t+2603.67613s: Requesting system shutdown...
cinnamon-session[753]: WARNING: t+2603.68579s: Attempting to shutdown using systemd...
cinnamon-session[753]: WARNING: t+2603.83087s: Application 'cinnamon-settings-daemon-wacom.desktop' killed by signal 15
cinnamon-session[753]: WARNING: t+2603.83097s: Application 'cinnamon-settings-daemon-housekeeping.desktop' killed by signal 15
cinnamon-session[753]: WARNING: t+2603.83099s: Application 'cinnamon-settings-daemon-power.desktop' killed by signal 15
cinnamon-session[753]: WARNING: t+2603.83100s: Application 'cinnamon-settings-daemon-automount.desktop' killed by signal 15
cinnamon-session[753]: WARNING: t+2603.83101s: Application 'cinnamon-settings-daemon-xrandr.desktop' killed by signal 15
cinnamon-session[753]: WARNING: t+2603.83102s: Application 'cinnamon-settings-daemon-keyboard.desktop' killed by signal 15
cinnamon-session[753]: WARNING: t+2603.83103s: Application 'cinnamon-settings-daemon-print-notifications.desktop' killed by signal 15
cinnamon-session[753]: WARNING: t+2603.83104s: Application 'cinnamon-settings-daemon-a11y-keyboard.desktop' killed by signal 15
cinnamon-session[753]: WARNING: t+2603.83105s: Application 'cinnamon-settings-daemon-media-keys.desktop' killed by signal 15
cinnamon-session[753]: WARNING: t+2603.83106s: Application 'cinnamon-settings-daemon-screensaver-proxy.desktop' killed by signal 15
cinnamon-session[753]: WARNING: t+2603.83107s: Application 'cinnamon-settings-daemon-a11y-settings.desktop' killed by signal 15
cinnamon-session[753]: WARNING: t+2603.83224s: Application 'cinnamon-settings-daemon-background.desktop' killed by signal 15
cinnamon-session[753]: WARNING: t+2603.83229s: Application 'cinnamon-settings-daemon-xsettings.desktop' killed by signal 15

**Comment by ghost** [comment]
> Maybe you could try switching to the default Cinnamon theme to see if that makes any difference.

Do you mean Adwaita GTK theme or the Cinnamon Desktop theme?

**Comment by geckolinux** [comment]
The Cinnamon desktop theme would be the first one to test.

**Comment by ghost** [comment]
> The Cinnamon desktop theme would be the first one to test.

Still having crashes, especially while changing directories in Nemo.

**Comment by amethylghostling** [comment]
This seems to be causing most of the crashes
>(cinnamon:2333): XApp-WARNING **: 22:14:11.746: Could not spawn StatusNotifier watcher (xapp-sn-watcher): Failed to execute child process “/usr/libexec/xapps/sn-watcher/xapp-sn-watcher” (No such file or directory)

(cinnamon:2333): XApp-WARNING **: 22:14:11.746: Support will be limited to native XAppStatusIcons only

**Comment by geckolinux** [comment]
Those are just warnings, I don't think they're the cause of the crash.

**Comment by ghost** [comment]
This seems to the error
> (cinnamon:9646): Clutter-CRITICAL **: 17:15:45.794: clutter_actor_iter_next: assertion 'ri->age == ri->root->priv->age' failed
Cinnamon warning: Log level 16: cinnamon_app_create_icon_texture: MetaWindow 0x55fd0ce52360 provided that does not match App 0x55fd0d42e800
Cinnamon warning: Log level 16: cinnamon_app_create_icon_texture: MetaWindow 0x55fd0ce52690 provided that does not match App 0x55fd0d42e800
Cinnamon warning: Log level 16: cinnamon_app_create_icon_texture: MetaWindow 0x55fd0ce52cf0 provided that does not match App 0x55fd0d42e800
(cinnamon:9646): Clutter-CRITICAL **: 17:23:44.262: clutter_actor_iter_next: assertion 'ri->age == ri->root->priv->age' failed
(cinnamon:9646): Clutter-CRITICAL **: 17:23:57.259: clutter_actor_iter_next: assertion 'ri->age == ri->root->priv->age' failed
(cinnamon:9646): Clutter-CRITICAL **: 17:23:57.290: clutter_actor_iter_next: assertion 'ri->age == ri->root->priv->age' failed
(cinnamon:9646): Clutter-CRITICAL **: 17:23:57.348: clutter_actor_iter_next: assertion 'ri->age == ri->root->priv->age' failed
(cinnamon:9646): Clutter-CRITICAL **: 17:24:56.340: clutter_actor_iter_next: assertion 'ri->age == ri->root->priv->age' failed
(cinnamon:9646): Clutter-CRITICAL **: 17:26:16.734: clutter_actor_iter_next: assertion 'ri->age == ri->root->priv->age' failed
(cinnamon:9646): Clutter-CRITICAL **: 17:26:21.738: clutter_actor_iter_next: assertion 'ri->age == ri->root->priv->age' failed
(cinnamon:9646): Clutter-CRITICAL **: 17:27:06.575: clutter_actor_iter_next: assertion 'ri->age == ri->root->priv->age' failed
Exception in thread Thread-2:
Traceback (most recent call last):
  File "/usr/lib64/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/usr/lib64/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/bin/cinnamon-launcher", line 78, in wait_for_process
    os.execvp(FALLBACK_COMMAND, (FALLBACK_COMMAND,) + FALLBACK_ARGS)
  File "/usr/lib64/python3.8/os.py", line 568, in execvp
    _execvpe(file, args)
  File "/usr/lib64/python3.8/os.py", line 610, in _execvpe
    raise last_exc
  File "/usr/lib64/python3.8/os.py", line 601, in _execvpe
    exec_func(fullname, *argrest)
FileNotFoundError: [Errno 2] No such file or directory

**Comment by geckolinux** [comment]
Looks like an upstream Cinnamon bug for sure. GeckoLinux doesn't modify any code or upstream packages.

**Comment by ghost** [comment]
Can confirm the bug also exists in the Live USB. Interestingly the issue does not happen if Cinnamon is running in Software Rendering Mode. I have submitted this [issue](https://github.com/linuxmint/cinnamon/issues/10802) on Cinnamon's github page.

**Comment by geckolinux** [comment]
Ah, that's a very significant finding. So it's probably something related to the graphics drivers. I wonder if this would make any difference?
https://github.com/geckolinux/geckolinux-project/issues/392#issuecomment-1134981929

**Comment by ghost** [comment]
Can you try installing GeckoLinux Rolling on spare hardware to test if the bug is not happening in the Live USB but in a freshly installed system as well? Then set the panel to intellihide or autohide and while it's hidden open nemo and change directories quickly 
I want to know this because I have made quite a drastic changes to my install like removing packages that I thought were unnecessary. I know that I should not have done that since this might be happening due to the lack of some library.
**Here is some of the core packages that I have removed**
>gnome theme accessibility
checkmedia
dracut-kiwi-live
dialog
f2fs-tools
gstreamer-plugins-farstream
hdparm
info
manufacturer-PPDs
ntfsprogs
rsync
wmctrl
xdg-menu
xorriso
atasmart
Unfiltered:libabw-0_1-1
libapr1-0
libapr-util1-0
libBasicUsageEnvironment1
libboost_date_time1_78_0
libboost_filesystem1_78_0
libboost_iostreams1_78_0
libboost_locale1_78_0
libbox2d2
libbrasero-burn3-1
libbrasero-media3-1
libbrasero-utils3-1
libcddb2
libcdr-0_1-1
libchromaprint1
libclucene-contribs-lib1
libclucene-core1
libclucene-shared1
libclutter-1_0-0
libclutter-gtk-1_0-0
libcogl20
libcogl-pango20
libdvbpsi10
libebml5
libe-book-0_1-1
libeot0
libepubgen-0_1-1
libetonyek-0_1-1
libexiv2-27
libexttextcat
libexttextcat-2_0-0
libfreehand-0_1-1
libglslang11
libgpgmepp6
libgroupsock30
libgspell-1-2
libgtksourceview-4-0
libidn12
libixion-0_16-0
libixml11
libkate1
liblangtag1
libliveMedia102
liblpsolve55-0
libmad0
libmatroska7
libmspub-0_1-1
libmwaw-0_3-3
libmythes-1_2-0
libnumbertext-1_0-0
libnumbertext-data
libodfgen-0_1-1
liborcus-0_16-0
libpagemaker-0_0-0
libpeas-1_0-0
libpeas-gtk-1_0-0
libplacebo157
libprojectM3
libQt5X11Extras5
libqxp-0_0-0
librasqal3
librdf
librevenge-0_0-0
librevenge-stream-0_0-0
libserf-1-1
libshaderc_shared1
libspeexdsp1 libSPIRV-Tools-suse23 libstaroffice-0_0-0 libtotem-plparser18 libupnp17 libUsageEnvironment3 libvisio-0_1-1 libvlc5 libvlccore9 libwpd-0_10-10 libwpg-0_3-3 libwps-0_4-4 libxcb-composite0 libxmlsec1-1 libxmlsec1-nss1 libzmf-0_0-0 totem-pl-parser typelib-1_0-GtkSource-4 typelib-1_0-Peas-1_0 atmel-firmware bcm20702a1-firmware libdaemon0 libpoppler116 nss-mdns pipewire-alsa poppler-tools python38-apipkg python38-cached-property python38-certifi python38-cffi python38-charset-normalizer python38-cryptography python38-dragonmapper python38-hanzidentifier python38-idna python38-iniconfig python38-loguru python38-prettytable python38-py python38-pycparser python38-pycups python38-pycurl python38-pyOpenSSL python38-requests python38-six python38-urllib3 python38-wcwidth python38-zhon python3-cupshelpers udev-configure-printer faenza-icon-theme gtk2-metatheme-mint gtk3-metatheme-mint yast2-printer ModemManager  xf86-video-intel jfsutils gtk2&3-greybird-theme virtualbox-guest-tools virtualbox-guest-x11 virtualbox-kmp-default

I tried my best to not remove essential packages. I am sorry, I know I should not have done it. Tried to keep broadcom, realtek and intel firmware. Removed feature I did not need like IPhone support etc

**Comment by amethylghostling** [comment]
@geckolinux Can you please try looking for the bug on your system or a freshly installed one? If it exists on the live USB, it should also exist on an fresh install or not.

**Comment by ghost** [comment]
Hey, can you test if the bug exists in a fresh install on real hardware in a fresh install by setting the panel to autohide and then in nemo quickly change directories from the sidebar? At the very least try it on your current install, so that I at least know if reinstalling is going to make a difference.
