### ISSUE TITLE
Is the project still continued?

### ISSUE THREAD

**Issue by CicadaSeventeen** [geckolinux/geckolinux-project#415]
Excuse me. I heard that you are going to do another distro basing on debian. At the same time I find GeckoLinux stop updating for months and not coming up with leap 15.4. So I wonder if this project is going to be continued or not.
Thanks.

**Comment by geckolinux** [comment]
Hi there, yes, there will be a new set of ISOs released soon. 
Please note that GeckoLinux does not need to be frequently updated by me since all the packages and repositories are managed by openSUSE (or Packman). New GeckoLinux releases are only needed to implement new features or to correct issues that are specific to the GeckoLinux configuration or the Calamares implementation. So users with existing installations can simply continue to update their systems from openSUSE, the process does not depend on me at all. And whether the ISOs are new are old they can be used for installing GeckoLinux on new systems and then upgrading the installation according to these instructions:
https://github.com/geckolinux/geckolinux-project/wiki#how-to-update-geckolinux
