### ISSUE TITLE
GeckoLinux Static LXQT.x86 Monitor Settings App Not Working Due to Required Kscreen5 apps not being installed by default

### ISSUE THREAD

**Issue by snowjonsnow** [geckolinux/geckolinux-project#416]
The Monitor Settings app for GeckoLinux_STATIC_LXQt.x86_64-153.220104.0.iso consistently fails to open on a newly installed system. The immediate workaround that worked to restore the same functionality, including use of an external monitor, was installing and using ARandR. It is available in YaST but not installed by default.

Afterward, I installed kscreen5, which restored functionality to LXQT's Monitor Settings app. It now loads through the GUI as it should.

I recommend that you add both kscreen5 and ARandR to the list of default apps in the LXQT version of GeckoLinux.

**Comment by geckolinux** [comment]
Hi there, thanks for reporting this. `kscreen5` definitely won't be installed by default as it brings along a huge stack of KDE dependencies. Would `ARandR` be sufficient?

**Comment by snowjonsnow** [comment]
ARandR provides an alternative for the same functionality, but it works outside of LXQT. You would probably need to update the documentation to indicate this differs from a standard LXQT installation and that ARandR should be used instead.

**Comment by geckolinux** [comment]
I see, so it does appear in the applications menu but not in the LXQt settings manager?

**Comment by snowjonsnow** [comment]
One more note - I just found this on the readme for lxqt-config-monitor. They appear to have made a change to add the kde dependencies.

"This tool lets you change monitor settings. It was based on lxrandr-qt but now uses libkscreen"

https://github.com/lxqt/lxqt-config/tree/master/lxqt-config-monitor

Regarding your question about the applications menu, ARandR does appear in the menu once it's installed but it's not part of LXQT or available through the LXQT settings manager.

**Comment by geckolinux** [comment]
Interesting, thanks for bringing that to my attention. There are currently sets of new Rolling and Static spins in `staging` folders on Sourceforge. I'll take a look at that aspect of LXQt for these upcoming editions both Rolling and Static, and you too feel free to do the same. Notice that the live system does include a bunch of KF5 libraries on all editions due to the Calamares installer, but when installed to the disk they get uninstalled (except on Plasma obviously). I wouldn't be opposed to having just a few KF5 libs on the final installed system in the case of LXQt, but it's usually all-or-nothing, installing something as simple as a KDE text editor usually brings along a massive number of KDE dependencies, which I try to avoid on GeckoLinux.

**Comment by snowjonsnow** [comment]
Thanks for the information. As a very new LXQT user, I think ARandR is easier to use than the default equivalent LXQT apps, but it might be confusing for someone looking for LXQT Monitor Settings based on what the docs are telling them. The current LXQT ISO seems to work perfectly well otherwise, after trying multiple distros and desktops to see which one might allow this 10 year old Thinkpad to function, more or less, as it did when it was new. This was the first I found.

**Comment by geckolinux** [comment]
Cool, glad it's generally working well. BTW another option that I've found to work very well on hardware even 17 years old is the Mate edition, might be worth trying too.

**Comment by geckolinux** [comment]
Looks like Kscreen5 does bring along a ton of KF5 dependencies, so ARandR will be included in the LXQt editions. Thanks for the useful suggestion.

**Comment by geckolinux** [comment]
Implemented in the latest GeckoLinux release.
