### ISSUE TITLE
Graphical error with GNOME

### ISSUE THREAD

**Issue by Befelec** [geckolinux/geckolinux-project#455]
After booting the rolling GNOME iso, the entire screen turned bright yellow. I recorded this - https://www.youtube.com/watch?v=6vxlNHGLhL8.
I decided to navigate the installer & install to check if it would work correctly, however it was exactly the same as in the video.

The sha1 & md5 checksums were both correct and I tried downloading the iso twice. 
Before I found this distro I installed openSUSE Tumbleweed with GNOME and it worked perfectly. 
I have an Nvidia GPU.

**Comment by geckolinux** [comment]
Hi there, is this with the GeckoLinux _Static_ or _Rolling_ ISO?

You could try this:
https://help.gnome.org/users/gnome-help/stable/color-calibrate-screen.html.en

This appears to be the same problem:
https://www.reddit.com/r/openSUSE/comments/s5qvhg/everything_is_yellow_on_opensuse_gnome_on_xorg/

It might have been fixed in openSUSE since the GeckoLinux ISO was released, please try updating the installed system:
`sudo zypper dup`

Finally, you could use the Wayland session by removing the file: `/etc/gdm/custom.conf` and rebooting.

**Comment by Befelec** [comment]
Thanks, I just needed to update.
