### ISSUE TITLE
Update STATIC versions to Leap 15.0 base

### ISSUE THREAD

**Issue by vpereira** [geckolinux/geckolinux-project#50]
Hi, now that SUSE is retiring SUSE Studio, did you export it already to build service? Any plan to support Leap:15.0?

**Comment by geckolinux** [comment]
Hi there, since Suse Studio shut down and given that GeckoLinux uses non-free packages from Packman, I can't use the new Suse Studio Express via OBS, which doesn't support external repos. So I'm now using a VPS to build images directly with Kiwi.

I'm currently working on updating the STATIC (Leap based) ISOs first, and then ROLLING (Tumbleweed based) will hopefully follow soon after. There are currently some bugs in both Leap and Tumbleweed that are holding up the process. Sorry for the delay.

**Comment by geckolinux** [comment]
All *STATIC* and *ROLLING* editions now updated.

- https://github.com/geckolinux/geckolinux-project/releases/tag/150.180607
- https://github.com/geckolinux/geckolinux-project/releases/tag/999.180607

**Comment by kameha** [comment]
Can't use live USB. Got grub messages telling me to... I don't even know what it wants me to do !
I made the USB key with LiLiUSB. Any Idea ?
edit : same problem with static and rolling, btw.

**Comment by geckolinux** [comment]
@kameha Hello, please try a different way of [flashing the USB key](https://github.com/geckolinux/geckolinux-project/wiki#how-to-create-a-bootable-geckolinux-usb-key). Also please verify the md5sum of your download, which might have been corrupted. If that doesn't help, we'll need a picture or something of your screen.

 Also please create a new issue instead of re-using an un-related one.
