### ISSUE TITLE
GeckoLinux NEXT Plasma update breaks plasma

### ISSUE THREAD

**Issue by Zahrun** [geckolinux/geckolinux-project#521]
I installed GeckoLinux NEXT Plasma in a VM for testing. After a clean install, I ran `sudo zypper up`, did the update, and rebooted.
After the reboot, plasma is broken. sddm cannot load the theme correctly, and after entering password, the plasma session dies and we come back to sddm.

**Comment by geckolinux** [comment]
Hi there, I would recommend that you migrate to something else, since SUSE and openSUSE will stop producing the Leap base system that GeckoLinux NEXT depends on after version 15.6.

**Comment by Zahrun** [comment]
Ok thank you for that information. I guess the next thing is slowroll. I might try that when it officially releases. Thank you for your work.

**Comment by geckolinux** [comment]
> Ok thank you for that information. I guess the next thing is slowroll. I might try that when it officially releases. Thank you for your work.

Yes, that sounds like a reasonable option. Since Slowroll is basically a snapshot of Tumbleweed at a point in time, what you could do is upgrade your GeckoLinux NEXT installation to Tumbleweed now, and you don't even need to keep updating it after that if you don't want constant change. Then once Slowroll is ready to go you could again switch the repos on your installation from Tumbleweed to Slowroll and start tracking that. Also you can read a few other thoughts I have on this situation in my post here:
https://github.com/geckolinux/geckolinux-project/discussions/519#discussioncomment-7217342
