### ISSUE TITLE
openSUSE > Gecko rebrand possibilities

### ISSUE THREAD

**Issue by jayarmstrong** [geckolinux/geckolinux-project#539]
Hi @geckolinux ,
The openSUSE community is rebranding and "Gecko" is one of the suggestions being discussed. It's understood this is your 'brand'. We're discussing many options, but if this is an option, it might be a win.

Would you consider releasing it / rebranding Gecko Linux to something else? I imagine you'd get a lot of help with a transition if you wanted it.

I don't represent the leadership or community -- just a member.

**Comment by geckolinux** [comment]
Hi there, thanks for asking. In my opinion it's not as much an issue of who has the right to use the branding as much as it is a question of how those namespaces are currently defined in the minds of most users. Rebranding attempts are notoriously hard to gain acceptance (i.e. Twitter -> X; or Chrysler -> Daimler-Chrysler -> FCA -> Stellantis), so openSUSE is going to have an uphill battle of leaving behind their fairly strong mindshare in the Linux community and becoming widely known by whatever new name they choose. Then add to that the additional confusion of their new name being based on the old name of a spinoff project that was named a long time ago as a reference to the mascot of the old openSUSE project... It sounds like a mess to me.

Tangentially, "Gecko" is a terrible name for SEO. I actually don't care about SEO as such, in fact I despise everything about that entire field. But the fact of the matter is that it's impossible to find specific and relevant information online about an OS with such a generic search term as "Gecko". That's why the current name of my project is neither `Gecko` nor `Gecko Linux` but rather `GeckoLinux`, and I always try to correct users that write it the wrong way. But even so they inevitably end up calling it "Gecko", which stinks when trying to locate relevant articles and posts about it. So openSUSE should take that into account as well when choosing their new name.

**Comment by jayarmstrong** [comment]
excellent points! Thanks. A new brand would also allow a more open horizon for wherever the project is heading now. It's not often a large community gets the chance to reinvent itself.
