### ISSUE TITLE
Donate

### ISSUE THREAD

**Issue by ghost** [geckolinux/geckolinux-project#66]
Is there any way to donate to you or do you suggest donating to the opensuse project?

**Comment by geckolinux** [comment]
Hi there, thanks very much for asking!

I first checked with openSUSE, and it appears that they are not able to receive monetary donations because of their legal situation. However, they do have a shop where you can buy openSUSE gear:
https://shop.opensuse.org

Since a few people have asked about this, I added a (completely optional and without any kind of coercion) donation button to the GeckoLinux page too:
http://geckolinux.github.io/#donate

Thanks again.

**Comment by geckolinux** [comment]
Hi there, thanks very much for asking!

I first checked with openSUSE, and it appears that they are not able to receive monetary donations because of their legal situation. However, they do have a shop where you can buy openSUSE gear:
https://shop.opensuse.org

Thanks again.

**Comment by ghost** [comment]
I got the point
