### ISSUE TITLE
Need termperature display: Psensor?

### ISSUE THREAD

**Issue by pccobbler** [geckolinux/geckolinux-project#89]
I would really like a package that displays temperatures of processor cores and drives. Psensor does that, but it's not available. Please add Psensor or something similar.

P.S. I meant temperature, not termperature.

**Comment by geckolinux** [comment]
Hi there, since GeckoLinux is not a fork or independent distro I can't add packages that aren't available yet for openSUSE. However, you could try adding on one of the 3rd party repositories that contain psensor:
https://software.opensuse.org/package/psensor
You could also request openSUSE to add psensor to their official repos.
