### ISSUE TITLE
right-mouse-click alternate menus via keyboard?

### ISSUE THREAD

**Issue by HacimLlih** [geckolinux/geckolinux-project#97]
Keyboard pc operations purist here. I'm on a Dell with no typical alternate menu key. On #windBLOWS, I can call it via keyboard via "Shift+F10". On my (now beloved & depended on) Tumbleweed GeckoLinux I cannot seem to find a keyboard way to call up said alt menus please? I've looked in Global Keyboard assignments and searched here on forum and Googled for this to no avail. Any clues appreciated.. and lastly.. 
**_THANKS for this great fork of USB Live Tumbleweed!! ;]]_**

**Comment by geckolinux** [comment]
Hi there, glad you like GeckoLinux! (It's technically not a "fork" of Tumbleweed, but rather a "spin", because it directly uses openSUSE's packages and repositories, and there are no independent GeckoLinux repositories.)

I really don't know the answer to your question. I would recommend posting it to:
https://forums.opensuse.org/

Cheers.
